apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: sample-mq
  namespace: cp4i
spec:
  license:
    accept: true
    license: L-RJON-BQPGWD
    use: NonProduction
  queueManager:
    name: MYQM
    storage:
      queueManager:
        type: ephemeral
    availability:
      type: SingleInstance
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.1.5.0-r2
  web:
    enabled: true